### ISSUE TITLE
Проблема с установкой

### ISSUE THREAD

**Issue by Andertaker** [ramusus/django-social-api#1]
https://github.com/ramusus/django-social-api/blob/master/social_api/storages/social_auth.py#L1

Вызывает ImportError
No module named social.apps.django_app.default.models

**Comment by ramusus** [comment]
В какой момент ошибка? пришли full traceback

**Comment by Andertaker** [comment]
[ImportError__at _instagram_fetch_group_.html.zip](https://github.com/ramusus/django-social-api/files/144675/ImportError__at._instagram_fetch_group_.html.zip)
