### ISSUE TITLE
Instagram provider

### ISSUE THREAD

**Issue by Andertaker** [ramusus/django-social-api#2]
Provider `instagram` not in available providers list
[ValueError__at _instagram_fetch_group_.html.zip](https://github.com/ramusus/django-social-api/files/147041/ValueError__at._instagram_fetch_group_.html.zip)

**Comment by ramusus** [comment]
@Andertaker Проверь, эту строчку у себя локально и обнови приложение, если ее нет https://github.com/ramusus/django-oauth-tokens/blob/master/oauth_tokens/models.py#L29
